### ISSUE TITLE
Does this project accept pull requests?

### ISSUE THREAD

**Issue by agoza** [iqfareez/app_waktu_solat_malaysia#126]
Salam, brother @iqfareez. I have suggestions for 3 files and wondering if you want to have a look. These are just minor changes to attempt my first pull request that I don't mind revising or getting rejected.

Salam. Kalau belum buat sendiri, saya nak cadangkan penambahbaikan kecil-kecilan untuk 3 fail. Nak practice sebab baru nak berkecimpung dalam bidang ni. Kalau okay saya fork, lepas tu nak bagi feedback atau reject pun tak apa.

![image](https://user-images.githubusercontent.com/49515501/173211106-9434d163-b54f-46b2-995c-bd68e0e2b0c1.png)

**Comment by iqfareez** [comment]
Waalaikumsalam. Thank you for your interest to this repo. Suree! PR is most welcomed regardless of any contribution you make. I'll take a look inshallah.
